بارگيري فايل از آدرس مورد نظر

In [ ]:
!wget https://archive.ics.uci.edu/static/public/45/heart+disease.zip

--2023-06-24 11:49:22--  https://archive.ics.uci.edu/static/public/45/heart+disease.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘heart+disease.zip’

heart+disease.zip       [ <=>                ] 125.87K   661KB/s    in 0.2s    

2023-06-24 11:49:22 (661 KB/s) - ‘heart+disease.zip’ saved [128894]



باز كردن فايل از حالت فشرده

In [ ]:
!unzip heart+disease.zip

Archive:  heart+disease.zip
  inflating: Index                   
  inflating: WARNING                 
  inflating: ask-detrano             
  inflating: bak                     
  inflating: cleve.mod               
  inflating: cleveland.data          
   creating: costs/
  inflating: costs/Index             
  inflating: costs/heart-disease.README  
  inflating: costs/heart-disease.cost  
  inflating: costs/heart-disease.delay  
  inflating: costs/heart-disease.expense  
  inflating: costs/heart-disease.group  
  inflating: heart-disease.names     
  inflating: hungarian.data          
  inflating: long-beach-va.data      
  inflating: new.data                
  inflating: processed.cleveland.data  
  inflating: processed.hungarian.data  
  inflating: processed.switzerland.data  
  inflating: processed.va.data       
  inflating: reprocessed.hungarian.data  
  inflating: switzerland.data        


فراخواني كتابخانه و بسته هاي مورد نياز

In [ ]:
import numpy as np
from collections import defaultdict
from sklearn.model_selection import train_test_split

data_path = 'bak'
# n_users = 6040
# n_movies = 3706



شماره ي ستون ها به ترتيب

1. #3  (age)
2. #4  (sex)
3. #9  (cp)
4. #10 (trestbps)
5. #12 (chol)
6. #16 (fbs)
7. #19 (restecg)
8. #32 (thalach)
9. #38 (exang)
10. #40 (oldpeak)
11. #41 (slope)
12. #44 (ca)
13. #51 (thal)
14. #58 (num)

خواندن فايل و قرار دادن در ليست

In [ ]:
data_path = 'bak'
data = []
with open(data_path, 'r') as file:
  for line in file.readlines():
    # print(line)
    line = line.split(",")
    line[-1] = int(line[-1])
    data.append(line)

print(data[:10])
total_rating_record = len(data)
print(total_rating_record)

[['63', '1', '4', '140', '260', '0', '1', '112', '1', '3', '2', '?', '?', 2], ['44', '1', '4', '130', '209', '0', '1', '127', '0', '0', '?', '?', '?', 0], ['60', '1', '4', '132', '218', '0', '1', '140', '1', '1.5', '3', '?', '?', 2], ['55', '1', '4', '142', '228', '0', '1', '149', '1', '2.5', '1', '?', '?', 1], ['66', '1', '3', '110', '213', '1', '2', '99', '1', '1.3', '2', '?', '?', 0], ['66', '1', '3', '120', '0', '0', '1', '120', '0', '-0.5', '1', '?', '2', 0], ['65', '1', '4', '150', '236', '1', '1', '105', '1', '0', '?', '?', '?', 3], ['60', '1', '3', '180', '0', '0', '1', '140', '1', '1.5', '2', '?', '?', 0], ['60', '1', '3', '120', '0', '?', '0', '141', '1', '2', '1', '?', '?', 3], ['60', '1', '2', '160', '267', '1', '1', '157', '0', '0.5', '2', '?', '?', 1]]
200


ميانگين گيري از ستون ها

In [ ]:
calc_list = [0 for i in range(14)]
feauter_count = [0 for i in range(14)]
for i in data:
  for j in range(len(calc_list)):
    if i[j] != '?':
      i[j] = float(i[j])
      calc_list[j] = calc_list[j] + i[j]
      feauter_count[j] += 1

for i in range(len(calc_list)):
  if i == 9:
    calc_list[i] = calc_list[i] / feauter_count[i]
  else:
    calc_list[i] = int(calc_list[i] / feauter_count[i])

print(calc_list)

[59, 0, 3, 133, 178, 0, 0, 122, 0, 1.3208333333333333, 2, 0, 5, 1]


جايگزيني علامت سوال ها با مقدار ميانگين

In [ ]:
for i in range(len(data)):
  for j in range(len(data[i])):
    if data[i][j] == '?':
      data[i][j] = calc_list[j]

print(data)
print(len(data))

[[63.0, 1.0, 4.0, 140.0, 260.0, 0.0, 1.0, 112.0, 1.0, 3.0, 2.0, 0, 5, 2.0], [44.0, 1.0, 4.0, 130.0, 209.0, 0.0, 1.0, 127.0, 0.0, 0.0, 2, 0, 5, 0.0], [60.0, 1.0, 4.0, 132.0, 218.0, 0.0, 1.0, 140.0, 1.0, 1.5, 3.0, 0, 5, 2.0], [55.0, 1.0, 4.0, 142.0, 228.0, 0.0, 1.0, 149.0, 1.0, 2.5, 1.0, 0, 5, 1.0], [66.0, 1.0, 3.0, 110.0, 213.0, 1.0, 2.0, 99.0, 1.0, 1.3, 2.0, 0, 5, 0.0], [66.0, 1.0, 3.0, 120.0, 0.0, 0.0, 1.0, 120.0, 0.0, -0.5, 1.0, 0, 2.0, 0.0], [65.0, 1.0, 4.0, 150.0, 236.0, 1.0, 1.0, 105.0, 1.0, 0.0, 2, 0, 5, 3.0], [60.0, 1.0, 3.0, 180.0, 0.0, 0.0, 1.0, 140.0, 1.0, 1.5, 2.0, 0, 5, 0.0], [60.0, 1.0, 3.0, 120.0, 0.0, 0, 0.0, 141.0, 1.0, 2.0, 1.0, 0, 5, 3.0], [60.0, 1.0, 2.0, 160.0, 267.0, 1.0, 1.0, 157.0, 0.0, 0.5, 2.0, 0, 5, 1.0], [56.0, 1.0, 2.0, 126.0, 166.0, 0.0, 1.0, 140.0, 0.0, 0.0, 2, 0, 5, 0.0], [59.0, 1.0, 4.0, 140.0, 0.0, 0.0, 1.0, 117.0, 1.0, 1.0, 2.0, 0, 5, 1.0], [62.0, 1.0, 4.0, 110.0, 0.0, 0.0, 0.0, 120.0, 1.0, 0.5, 2.0, 0, 3.0, 1.0], [63.0, 1.0, 3.0, 133, 0.0, 0.0, 2.0, 1

جداسازي داده هاي آموزش و تست

In [ ]:
data_train, data_test = train_test_split(data,
                                        test_size=0.2,
                                        random_state=42)
print(data_train[:10])
print("Training data length:")
print(len(data_train))

print(data_test[:10])
print("Test data length:")
print(len(data_test))

[[64.0, 0.0, 4.0, 142.0, 276.0, 0.0, 0.0, 140.0, 1.0, 1.0, 2.0, 0, 7.0, 1.0], [55.0, 1.0, 4.0, 122.0, 223.0, 1.0, 1.0, 100.0, 0.0, 0.0, 2, 0, 6.0, 2.0], [58.0, 1.0, 4.0, 133, 203.0, 1.0, 0.0, 122, 0, 1.3208333333333333, 2, 0, 5, 1.0], [52.0, 1.0, 3.0, 128.0, 0.0, 0.0, 1.0, 180.0, 0.0, 3.0, 1.0, 0, 5.0, 2.0], [54.0, 1.0, 4.0, 130.0, 202.0, 1.0, 0.0, 112.0, 1.0, 2.0, 2.0, 0, 5, 1.0], [54.0, 0.0, 4.0, 127.0, 333.0, 1.0, 1.0, 154.0, 0.0, 0.0, 2, 0, 5, 1.0], [55.0, 1.0, 3.0, 133, 228.0, 0.0, 1.0, 122, 0, 1.3208333333333333, 2, 0, 5, 3.0], [60.0, 1.0, 4.0, 152.0, 0.0, 0.0, 1.0, 118.0, 1.0, 0.0, 2, 0, 7.0, 0.0], [64.0, 1.0, 4.0, 134.0, 273.0, 0.0, 0.0, 102.0, 1.0, 4.0, 3.0, 0, 5, 4.0], [69.0, 1.0, 4.0, 140.0, 208.0, 0.0, 1.0, 140.0, 1.0, 2.0, 2, 0, 5, 3.0]]
Training data length:
160
[[63.0, 1.0, 4.0, 160.0, 267.0, 1.0, 1.0, 88.0, 1.0, 2.0, 2, 0, 5, 3.0], [62.0, 1.0, 4.0, 120.0, 220.0, 0.0, 1.0, 86.0, 0.0, 0.0, 2, 0, 5, 0.0], [54.0, 1.0, 4.0, 133, 0.0, 0.0, 1.0, 122, 0, 1.3208333333333333, 2, 

# New syntax

استفاده از بسته ي sklearn

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
clf = MultinomialNB(alpha=1.0, fit_prior=True)

In [ ]:
X_train = [data_train[i][:13] for i in range(len(data_train))]
print(X_train)

Y_train = [data_train[i][13] for i in range(len(data_train))]
print(Y_train)

X_test = [data_test[i][:13] for i in range(len(data_test))]
print(X_test)

Y_test = [data_test[i][13] for i in range(len(data_test))]
print(Y_test)

[[64.0, 0.0, 4.0, 142.0, 276.0, 0.0, 0.0, 140.0, 1.0, 1.0, 2.0, 0, 7.0], [55.0, 1.0, 4.0, 122.0, 223.0, 1.0, 1.0, 100.0, 0.0, 0.0, 2, 0, 6.0], [58.0, 1.0, 4.0, 133, 203.0, 1.0, 0.0, 122, 0, 1.3208333333333333, 2, 0, 5], [52.0, 1.0, 3.0, 128.0, 0.0, 0.0, 1.0, 180.0, 0.0, 3.0, 1.0, 0, 5.0], [54.0, 1.0, 4.0, 130.0, 202.0, 1.0, 0.0, 112.0, 1.0, 2.0, 2.0, 0, 5], [54.0, 0.0, 4.0, 127.0, 333.0, 1.0, 1.0, 154.0, 0.0, 0.0, 2, 0, 5], [55.0, 1.0, 3.0, 133, 228.0, 0.0, 1.0, 122, 0, 1.3208333333333333, 2, 0, 5], [60.0, 1.0, 4.0, 152.0, 0.0, 0.0, 1.0, 118.0, 1.0, 0.0, 2, 0, 7.0], [64.0, 1.0, 4.0, 134.0, 273.0, 0.0, 0.0, 102.0, 1.0, 4.0, 3.0, 0, 5], [69.0, 1.0, 4.0, 140.0, 208.0, 0.0, 1.0, 140.0, 1.0, 2.0, 2, 0, 5], [50.0, 1.0, 4.0, 133, 218.0, 0.0, 0.0, 122, 0, 1.3208333333333333, 2, 0, 5], [74.0, 1.0, 3.0, 140.0, 237.0, 1.0, 0.0, 94.0, 0.0, 0.0, 2, 0, 5], [66.0, 1.0, 3.0, 120.0, 0.0, 0.0, 1.0, 120.0, 0.0, -0.5, 1.0, 0, 2.0], [54.0, 0.0, 4.0, 138.0, 274.0, 0.0, 0.0, 105.0, 1.0, 1.5, 2.0, 0, 5], [63.

In [ ]:
from sklearn.preprocessing import MinMaxScaler #fixed import

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
clf.fit(X_train, Y_train)

MultinomialNB()

In [ ]:
prediction_prob = clf.predict_proba(X_test)

In [ ]:
print(prediction_prob[0:10])

[[0.17676163 0.32840392 0.21113012 0.22557389 0.05813044]
 [0.33221586 0.24764385 0.18903728 0.20301245 0.02809055]
 [0.33378317 0.24752752 0.19606393 0.19343196 0.02919342]
 [0.31763978 0.2873825  0.17417981 0.17945219 0.04134572]
 [0.17005068 0.36055949 0.20167921 0.21589174 0.05181887]
 [0.32156651 0.28713507 0.1700411  0.17895727 0.04230005]
 [0.33274427 0.27810919 0.16820431 0.17530588 0.04563634]
 [0.18438819 0.29200529 0.2319603  0.25904141 0.03260482]
 [0.35445099 0.2298302  0.18472607 0.19968195 0.0313108 ]
 [0.17427107 0.30518874 0.24170556 0.25091138 0.02792325]]


In [ ]:
prediction = clf.predict(X_test)

In [ ]:
print(prediction[:])

[1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 3. 1. 0.
 0. 0. 3. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
accuracy = clf.score(X_test, Y_test)

In [ ]:
print(f'The accuracy is: {accuracy*100:.1f}%')

The accuracy is: 25.0%
